Add `-s` option to `neuro image tags` to print sizes of corresponding images
neuro-inc/platform-client-python pull request #1856
Opened 2020-11-20 09:55 UTC by anayden

Work in progress.

2020-11-25 10:36 UTC, yartem commented
Minor: I'm getting badly formatted output "Tags for <image_name>...":
![image](https://user-images.githubusercontent.com/7501517/100215205-c88c5b80-2f21-11eb-83a5-a3aba0b74706.png)

2020-11-25 10:43 UTC, anayden commented
Good point. Fixed the issue

2020-11-25 12:41 UTC, asvetlov requested changes
Please document the new API

2020-11-27 11:15 UTC, asvetlov commented on docs/images_reference.rst
> +      :return: tag information (name and size) (:class: `Tag`)
```suggestion
      :return: tag information (name and size) (:class:`Tag`)
```

2020-11-27 11:17 UTC, asvetlov approved these changes

2020-12-02 12:12 UTC, merged